<?php
    include("index.html");
?>

<section  class="parallax">

    <section class="id_">
    <h1>اگر به مشکلی برخورده اید باما تماس بگیرید</h1>
        <P>
        1.	عینک واقعیت مجازی سامسونگ مدل Oculus 2017
        </P>
        <P>
        echo "# index" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/mohhamadAminHajjaty/index.git
git push -u origin main
        </P>
    </section>
    </section>